# Generated by Django 2.2 on 2021-03-18 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addons_forward', '0001_initial'),
        ('osf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodesettings',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addons_forward_node_settings', to='osf.AbstractNode'),
        ),
    ]
